/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#574500',
        'on-background': '#1b1c14',
        'surface-dim': '#dbdbcd',
        'on-primary-container': '#554300',
        'surface-variant': '#e3e3d5',
        'surface-bright': '#fafaeb',
        secondary: '#904d00',
        'surface-container': '#efefe0',
        'on-tertiary-fixed': '#001f24',
        'surface-container-high': '#e9e9db',
        'tertiary-fixed': '#a7eefa',
        'on-secondary-fixed': '#2f1500',
        primary: '#735c00',
        'secondary-container': '#fd8b00',
        'inverse-surface': '#2f3128',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#603100',
        'secondary-fixed': '#ffdcc3',
        'inverse-primary': '#e9c349',
        'on-surface-variant': '#4d4635',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#8bd2dd',
        'surface-container-highest': '#e3e3d5',
        'tertiary-container': '#77bec9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f5e6',
        'primary-container': '#d4af37',
        'on-tertiary-container': '#004d55',
        'on-secondary-fixed-variant': '#6e3900',
        'primary-fixed': '#ffe088',
        'inverse-on-surface': '#f1f2e3',
        'surface-tint': '#735c00',
        'primary-fixed-dim': '#e9c349',
        background: '#fafaeb',
        'error-container': '#ffdad6',
        tertiary: '#156872',
        'on-primary-fixed': '#241a00',
        'outline-variant': '#d0c5af',
        'on-tertiary-fixed-variant': '#004f57',
        'secondary-fixed-dim': '#ffb77d',
        surface: '#fafaeb',
        outline: '#7f7663',
        'on-error-container': '#93000a',
        'on-surface': '#1b1c14',
        'on-secondary': '#ffffff',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'section-padding-lg': '120px',
        'container-max': '1440px',
        'section-padding-md': '80px',
        'margin-mobile': '20px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'label-caps': ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        'headline-lg': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'body-md': ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        'display-lg-mobile': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'display-lg': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'headline-md': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'body-lg': ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.15em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0',
        lg: '0',
        xl: '0',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
